In [14]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))





[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
print(a + 10)
print(a * 2)
print(a ** 2)

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [16]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b.ndim)


(2, 3)
2


In [17]:
print(np.mean(a))
print(np.sum(a))
print(np.max(a))
print(np.min(a))

3.0
15
5
1


In [18]:
print(np.zeros(5))
print(np.ones(5))
print(np.arange(0, 10, 2))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]


In [19]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])      # first element
print(a[-1])     # last element
print(a[1:4])    # middle slice


10
50
[20 30 40]


In [20]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0])       # first row
print(b[:, 0])    # first column
print(b[1, 2])    # row 1, column 2

[1 2 3]
[1 4 7]
6


In [21]:
np.random.seed(42)
print(np.random.randint(0, 100, 5))
print(np.random.rand(3, 3))


[51 92 14 71 60]
[[0.59685016 0.44583275 0.09997492]
 [0.45924889 0.33370861 0.14286682]
 [0.65088847 0.05641158 0.72199877]]


In [24]:
# Reshaping - very important in ML
a = np.arange(1, 10)
print(a.reshape(3, 3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
marks = np.array([45, 80, 30, 90, 55])
print(marks[marks > 50])

[80 90 55]


In [26]:
# Linear algebra basics - core of ML
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))        # matrix multiplication
print(np.transpose(a))     # transpose


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [27]:
data = np.array([23, 45, 12, 67, 34, 89, 56])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std Dev:", np.std(data))
print("Variance:", np.var(data))

Mean: 46.57142857142857
Median: 45.0
Std Dev: 24.546498981420914
Variance: 602.530612244898


In [28]:
print("Sorted:", np.sort(data))
print("Reverse sorted:", np.sort(data)[::-1])
print("Index of max:", np.argmax(data))
print("Index of min:", np.argmin(data))


Sorted: [12 23 34 45 56 67 89]
Reverse sorted: [89 67 56 45 34 23 12]
Index of max: 5
Index of min: 2


In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertical stack:\n", np.vstack([a, b]))
print("Horizontal stack:", np.hstack([a, b]))

Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]


In [30]:
marks = np.array([55, 40, 78, 33, 90, 61])
passed = marks[marks >= 50]
failed = marks[marks < 50]

print("Passed:", passed)
print("Failed:", failed)
print("Pass percentage:", len(passed)/len(marks)*100, "%")

Passed: [55 78 90 61]
Failed: [40 33]
Pass percentage: 66.66666666666666 %


In [31]:
# Why NumPy over Python lists?
list1 = list(range(1000000))
arr1 = np.arange(1000000)

import time

start = time.time()
result = [x*2 for x in list1]
print("List time:", time.time() - start)

start = time.time()
result = arr1 * 2
print("NumPy time:", time.time() - start)

List time: 0.0271298885345459
NumPy time: 0.015276670455932617


In [32]:
# Normalization - used in every ML model
data = np.array([100, 200, 300, 400, 500])

normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized:", normalized)


Normalized: [0.   0.25 0.5  0.75 1.  ]


In [33]:
# Correlation - finding relationship between variables
height = np.array([150, 160, 170, 180, 190])
weight = np.array([50, 60, 70, 80, 90])

correlation = np.corrcoef(height, weight)
print("Correlation matrix:\n", correlation)
print("Correlation value:", correlation[0][1])
# closer to 1 = strong positive relationship
# closer to -1 = strong negative relationship
# closer to 0 = no relationship

Correlation matrix:
 [[1. 1.]
 [1. 1.]]
Correlation value: 1.0


In [36]:
# In ML we split data into training and testing
data = np.arange(1, 101)   # 100 samples

# Shuffle first
np.random.seed(42)
np.random.shuffle(data)

# 80% train, 20% test
split = int(0.8 * len(data))
train = data[:split]
test = data[split:]

print("Train size:", len(train))
print("Test size:", len(test))
print("Train data:", train[:5])
print("Test data:", test[:5])

Train size: 80
Test size: 20
Train data: [84 54 71 46 45]
Test data: [64 85 38 30  2]


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
