In [14]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))





[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
print(a + 10)
print(a * 2)
print(a ** 2)

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [16]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b.ndim)


(2, 3)
2


In [17]:
print(np.mean(a))
print(np.sum(a))
print(np.max(a))
print(np.min(a))

3.0
15
5
1


In [18]:
print(np.zeros(5))
print(np.ones(5))
print(np.arange(0, 10, 2))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]


In [19]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])      # first element
print(a[-1])     # last element
print(a[1:4])    # middle slice


10
50
[20 30 40]


In [20]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0])       # first row
print(b[:, 0])    # first column
print(b[1, 2])    # row 1, column 2

[1 2 3]
[1 4 7]
6


In [21]:
np.random.seed(42)
print(np.random.randint(0, 100, 5))
print(np.random.rand(3, 3))


[51 92 14 71 60]
[[0.59685016 0.44583275 0.09997492]
 [0.45924889 0.33370861 0.14286682]
 [0.65088847 0.05641158 0.72199877]]


In [24]:
# Reshaping - very important in ML
a = np.arange(1, 10)
print(a.reshape(3, 3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
marks = np.array([45, 80, 30, 90, 55])
print(marks[marks > 50])

[80 90 55]
